apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: cluster-dev
spec:
  topology:
    controlPlane:
      count: 1
      class: best-effort-xsmall # vmclass to be used for master(s)
      storageClass: wcp-storage-policy
    workers:
      count: 2
      class: best-effort-xsmall # vmclass to be used for workers(s)
      storageClass: wcp-storage-policy
  distribution:
    version: v1.15.5+vmware.1-tkg.1.85123d8
  settings:
    network:
      cni:
        name: calico
      services:
        cidrBlocks: ["10.151.0.0/22"]
      pods:
        cidrBlocks: ["10.51.0.0/20"]
